learning_rate: 0.001
epochs: 250
batch_size: 16
optimizer: adam
weight_decay: 0.5
loss: categorical_cross_entropy

input_layers:
  - size: 30

hidden_layers:
  - size: 24
    activation: relu
    initializer: he
  - size: 12
    activation: relu
    initializer: he

output_layers:
  - size: 2
    activation: softmax
    initializer: xavier
